{"name": "test_change_object_put", "status": "failed", "statusDetails": {"message": "AssertionError: Object {'name'} wasn't created.", "trace": "create_new_obj_endpoint = <endpoints.create_obj.CreateObject object at 0x000002E541B85160>\n\n    @pytest.fixture()\n    def create_obj(create_new_obj_endpoint):\n        body = {\n            \"name\": \"New_obj_DKA2805\",\n            \"data\": {\n                \"year\": 1982,\n                \"price\": 2805.99,\n                \"CPU model\": \"Intel Core i9DKA\",\n                \"Hard disk size\": \"1 TB DKA\"\n            }\n        }\n        create_new_obj_endpoint.create_new_obj(body)\n>       create_new_obj_endpoint.check_obj_name({\"name\"})\n\nconftest.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <endpoints.create_obj.CreateObject object at 0x000002E541B85160>, name = {'name'}\n\n    @allure.step('Проверяем имя созданного объекта.')\n    def check_obj_name(self, name):\n>       assert self.obj_json['name'] == name, f\"Object {name} wasn't created.\"\nE       AssertionError: Object {'name'} wasn't created.\n\nendpoints\\create_obj.py:23: AssertionError"}, "start": 1713417423694, "stop": 1713417423694, "uuid": "ba8f97de-15df-4432-8c44-40d3200d054e", "historyId": "f4c87fe456be1cc4f8a0807b04e51049", "testCaseId": "f4c87fe456be1cc4f8a0807b04e51049", "fullName": "tests.test_some_app#test_change_object_put", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_some_app"}, {"name": "host", "value": "Kirill"}, {"name": "thread", "value": "4324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_some_app"}]}