{"uuid": "3547fbe2-4070-4c31-b595-6fa893c1f7a4", "children": ["cbe93e47-fb31-4099-b1db-8740162f3e81"], "befores": [{"name": "create_del_new_obj", "status": "broken", "statusDetails": {"message": "KeyError: 'name'\n", "trace": "  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Kirill_Dechko\\homework\\kirill_dechko\\lesson_19_Pytest\\conftest.py\", line 35, in create_del_new_obj\n    assert response['name'] == f\"New_obj_{random.randint}\", \"Incorrect random int\"\n"}, "start": 1713082173877, "stop": 1713082174498}], "start": 1713082173877, "stop": 1713082174508}